CREATE TABLE expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(200) NOT NULL,
    amount NUMERIC(19, 4) NOT NULL CHECK (amount > 0),
    currency VARCHAR(3) NOT NULL,
    expense_date DATE NOT NULL,
    category VARCHAR(80) NOT NULL,
    notes VARCHAR(2000),
    paid_by BIGINT NOT NULL CHECK (paid_by > 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_expenses_expense_date ON expenses (expense_date);
CREATE INDEX idx_expenses_paid_by ON expenses (paid_by);
CREATE INDEX idx_expenses_category ON expenses (category);
