spring:
  application:
    name: expense
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/expense_analyzer}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:fkhr}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
server:
  port: ${SERVER_PORT:8087}
  shutdown: graceful

spring.data.web.pageable:
  max-page-size: 100

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /openapi.yaml
    disable-swagger-default-url: true
    display-request-duration: true
